'use client'

import Link from 'next/link'
import { Camera, CalendarDays, IndianRupee, UserRound } from 'lucide-react'
import { useApp } from '@/context/AppContext'
import { CitizenFooter, CitizenHeading, CitizenPage, SectionCard, statusClass, statusLabel } from '@/components/citizen-shell'

export default function CitizenWorksPage() {
  const { projects } = useApp()
  const localProjects = projects.filter((project) => project.district === 'Varanasi')
  return <CitizenPage><CitizenHeading eyebrow="Varanasi · Public works" title="Local works near you" copy="A simple view of public projects in your district. Check the latest status, see who is responsible, and share what you see on the ground." /><div className="grid gap-5 md:grid-cols-2">{localProjects.concat([{ id: 'VAR-256', name: 'Community Solar Street Lights · Ward 12', district: 'Varanasi', mp: 'Shri Narendra Modi', contractor: 'Kashi Civic Works', allocation: '₹74 L', progress: 58, status: 'On track' as const, lastUpdate: 'Today', category: 'Energy' }]).map((project) => <SectionCard key={project.id} className="flex flex-col"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">{project.category} · {project.id}</p><h2 className="mt-2 font-serif text-xl font-semibold">{project.name}</h2></div><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${statusClass(project.status)}`}>{statusLabel(project.status)}</span></div><div className="mt-6 grid grid-cols-3 gap-3 border-y border-border py-4 text-sm"><div><IndianRupee size={14} className="mb-1 text-muted-foreground" /><p className="font-semibold">{project.allocation}</p><p className="text-xs text-muted-foreground">Sanctioned</p></div><div><CalendarDays size={14} className="mb-1 text-muted-foreground" /><p className="font-semibold">{project.progress > 70 ? 'Sep 2026' : 'Dec 2026'}</p><p className="text-xs text-muted-foreground">Est. completion</p></div><div><UserRound size={14} className="mb-1 text-muted-foreground" /><p className="truncate font-semibold">{project.mp.replace('Shri ', '')}</p><p className="text-xs text-muted-foreground">Local MP</p></div></div><div className="mt-auto flex items-center justify-between pt-5"><div className="text-xs text-muted-foreground">{project.progress}% reported complete</div><Link href={`/citizen/verify?project=${project.id}`} className="flex items-center gap-2 rounded-lg bg-[#5f7f66] px-3 py-2 text-xs font-semibold text-white"><Camera size={14} />Upload ground photo</Link></div></SectionCard>)}</div><CitizenFooter /></CitizenPage>
}
