'use client'

import Link from 'next/link'
import { ArrowLeft, ArrowUpRight, MapPin, ShieldAlert } from 'lucide-react'
import dynamic from 'next/dynamic'
import { intelligenceProjects, riskColors, riskClass } from '@/data/intelligenceData'

const IndiaLeafletMap = dynamic(() => import('@/components/india-leaflet-map'), { ssr: false })

export default function MapPage() { return <main className="min-h-screen bg-background px-5 py-6 lg:px-10"><div className="mx-auto max-w-[1500px]"><div className="flex flex-wrap items-center gap-3"><Link href="/" className="inline-flex items-center gap-2 text-xs font-semibold text-muted-foreground hover:text-foreground"><ArrowLeft size={15}/> Dashboard</Link><Link href="/fraud-network" className="inline-flex items-center gap-2 rounded-lg border border-border bg-card px-3 py-2 text-xs font-semibold text-foreground hover:bg-muted">Open macro fraud network <ArrowUpRight size={14}/></Link></div><div className="mt-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="eyebrow">Step 2 · Geopolitical intelligence</p><h1 className="mt-2 font-serif text-4xl font-semibold tracking-tight">India project risk map</h1><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">A live geographic view of MPLADS projects, with color-coded risk signals and direct access to micro-case intelligence.</p></div><div className="flex flex-wrap gap-2 text-xs">{Object.entries(riskColors).map(([label,color]) => <span key={label} className="flex items-center gap-2 rounded-full border border-border bg-card px-3 py-2"><i className="h-2.5 w-2.5 rounded-full" style={{backgroundColor:color}}/>{label}</span>)}</div></div><div className="mt-8 grid gap-6 xl:grid-cols-[1.5fr_0.7fr]"><section className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-border px-5 py-4"><div><p className="text-sm font-semibold">Project distribution by state</p><p className="mt-1 text-xs text-muted-foreground">Markers render directly without fly-to animation.</p></div><span className="rounded-lg bg-muted px-3 py-2 text-xs font-semibold">{intelligenceProjects.length} active cases</span></div><div className="p-4"><IndiaLeafletMap /></div></section><aside className="panel overflow-hidden"><div className="border-b border-border px-5 py-4"><p className="text-sm font-semibold">Risk watchlist</p><p className="mt-1 text-xs text-muted-foreground">Select a marker or case to open full intelligence.</p></div><div className="divide-y divide-border">{intelligenceProjects.slice(0,7).map((project) => <Link key={project.id} href={`/work/${project.id}`} className="block p-4 transition hover:bg-muted/60"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold">{project.name}</p><p className="mt-1 flex items-center gap-1 text-[11px] text-muted-foreground"><MapPin size={12}/>{project.district}, {project.state}</p></div><ArrowUpRight size={14} className="text-muted-foreground"/></div><div className="mt-3 flex items-center justify-between"><span className={`status-pill ${riskClass(project.risk)}`}>{project.risk}</span><span className="font-mono text-[11px] text-muted-foreground">Score {project.score}</span></div></Link>)}</div></aside></div></div></main> }
